server/apps/base/urls.py
from django.urls import path

from server.apps.base.views import AboutView, ContactView, HomeView

app_name = "base"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact/", ContactView.as_view(), name="contact"),
]

server/apps/portfolio/urls.py
from django.urls import path

from server.apps.portfolio.views import CategoryView, PortfolioView, ProjectView

app_name = "portfolio"

urlpatterns = [
    path("", PortfolioView.as_view(), name="portfolio"),
    path("<int:pk>/", ProjectView.as_view(), name="project"),
    path("category/<int:pk>/", CategoryView.as_view(), name="category"),
]

server/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path

from server.apps.base.views import IndexView

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path("", include("server.apps.base.urls", namespace="base")),
    path("portfolio/", include("server.apps.portfolio.urls", namespace="portfolio")),
)

urlpatterns += [
    path("i18n/", include("django.conf.urls.i18n")),
]

urlpatterns += [path("", IndexView.as_view(), name="index")]

if "rosetta" in settings.INSTALLED_APPS:
    urlpatterns += [path("translations/", include("rosetta.urls"))]

# Django Health Check
urlpatterns += [
    path("health/", include("health_check.urls")),
]

if settings.DEBUG:
    from django.conf.urls.static import static  # noqa: WPS433

    # Django Debug Toolbar
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

    # Serving media files in development only:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

server/apps/base/models.py
from django.db import models


class Contact(models.Model):
    """Model definition for Contact."""

    email = models.EmailField(max_length=254)
    phone = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    instagram = models.URLField(max_length=200)
    facebook = models.URLField(max_length=200)

    class Meta:
        """Meta definition for Contact."""

        verbose_name = "Contact Details"
        verbose_name_plural = "Contact Details"

    def __str__(self):
        """Unicode representation of Contact."""
        return "Contact Details"


class Message(models.Model):
    """Model definition for Message."""

    name = models.CharField(max_length=50)

    email = models.EmailField(max_length=254)
    phone = models.CharField(max_length=50)

    subject = models.CharField(max_length=50)
    message = models.TextField(max_length=500)

    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        """Meta definition for Message."""

        verbose_name = "Message"
        verbose_name_plural = "Messages"

    def __str__(self):
        """Unicode representation of Message."""
        return self.name

server/apps/base/forms.py
from django import forms

from server.apps.base.models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ["name", "email", "phone", "subject", "message"]

server/apps/base/logic/forms.py
from django import forms

from server.apps.base.models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = (
            "name",
            "email",
            "phone",
            "subject",
            "message",
        )

server/apps/base/views.py
from django.shortcuts import HttpResponse
from django.urls import reverse
from django.utils import translation
from django.views.generic import RedirectView, TemplateView

from server.apps.base.logic.forms import MessageForm
from server.apps.portfolio.models import Project


class IndexView(RedirectView):
    """Index view."""

    def get_redirect_url(self, *args, **kwargs):
        translation.activate("az")
        return reverse("base:home")


class HomeView(TemplateView):
    """Home view."""

    template_name = "base/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["title"] = "Home"

        context["projects"] = Project.objects.all().order_by("-modified_at")[:4]

        return context


class AboutView(TemplateView):
    """About view."""

    template_name = "base/about.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["title"] = "About"

        return context


class ContactView(TemplateView):
    """Contact view."""

    template_name = "base/contact.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["title"] = "Contact"

        context["form"] = MessageForm()

        return context

    def post(self, request, *args, **kwargs):
        form = MessageForm(request.POST)

        if form.is_valid() and request.accepts("application/json"):
            form.save()

            return HttpResponse("Message sent successfully")

        return HttpResponse("Please fill all the fields correctly!", status=400)

server/apps/base/templates/base/index.html
{% extends 'base/layout.html' %}

{% load static %}

{% load i18n %}

{% block content %}
<!-- Hero Section -->
<section class="codeshift-hero-section pb-90 pt-80">
  <div class="shape shape__1 position-absolute wow fadeInUp" data-wow-delay="300ms" data-wow-duration="800ms">
    <img src="{% static 'assets/images/shapes/hero-shape-1.png' %}" alt="" />
  </div>
  <div class="shape shape__2 position-absolute wow fadeInUp" data-wow-delay="600ms" data-wow-duration="800ms">
    <img src="{% static 'assets/images/shapes/hero-shape-2.png' %}" alt="" />
  </div>
  <div class="container">
    <div class="row flex-lg-row flex-md-column-reverse">
      <div class="col-xl-5 col-lg-5">
        <div class="inner-content">
          <h1 class="title wow fadeInUp" data-wow-delay="200ms" data-wow-duration="800ms">
            {% trans 'Empower your business with innovative digital solutions.' %}
          </h1>
          <div class="inner-btns mt-50">
            <a href="{% url 'portfolio:portfolio' %}" class="codeshift-btn wow fadeInUp" data-wow-delay="500ms"
              data-wow-duration="800ms">{% trans 'Our Projects' %}<span></span></a>
          </div>
          <div class="codeshift-social-links mt-140">
            <a href="{{ facebook }}" class="wow fadeInUp" data-wow-delay="200ms" data-wow-duration="800ms"
              target="_blank">
              <i class="fab fa-facebook-f"></i> <span>Facebook</span>
            </a>
            <a href="{{ instagram }}" class="wow fadeInUp" data-wow-delay="800ms" data-wow-duration="800ms"
              target="_blank">
              <i class="fab fa-instagram"></i> <span>Instagram</span>
            </a>
          </div>
        </div>
      </div>
      <div class="col-xl-7 col-lg-7">
        <div class="inner-right">
          <div class="review-wrapper">
            <div class="item">
              <div class="icon">
                <img src="{% static 'assets/images/icons/growth.png' %}" alt="" />
              </div>
              <div class="content">
                <h6>100% {% trans 'Business Growth' %}</h6>
                <p><i class="fas fa-star"></i> <span>4.9</span></p>
              </div>
            </div>
            <div class="item">
              <div class="content">
                <h6>40+ {% trans 'Happy Clients' %}</h6>
                <p><i class="fas fa-star"></i> <span>4.9</span></p>
              </div>
            </div>
          </div>
          <div class="img-wrapper wow zoomIn" data-wow-delay="700ms" data-wow-duration="800ms">
            <img style="margin-bottom: 53px" src="{% static 'assets/images/hero/work.png' %}" alt="" />
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Project Section -->
<div class="codeshift-project-section pt-130 pb-130 theme-light-bg">
  <div class="container">
    <div class="row">
      <div class="col-xl-4">
        <div class="content-left-wrapper">
          <div class="codeshift-section-heading">
            <span class="sub-heading">{% trans 'RECENT PROJECTS' %}</span>
            <h2 class="heading mb-25">{% trans 'Our latest projects' %}</h2>
            <p>
              {% blocktrans %}
              Since 2015 we have been a visionary and a reliable software engineering partner for national brands.
              {% endblocktrans %}
            </p>
          </div>
          <a href="{% url 'portfolio:portfolio' %}" class="codeshift-btn mt-45">
            {% trans 'More Projects'%}
            <span></span>
          </a>
        </div>
      </div>
      <div class="col-xl-8">
        <div class="codeshift-project-wrapper">
          <div class="row codeshift-project-grid mt-none-30">
            {% for item in projects %}
            <!-- Item -->
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 mt-30 grid">
              <div class="codeshift-project-item">
                <div class="thumb">
                  <img class="home-project-img" src="{{ item.cover.url }}" alt="" />
                </div>
                <div class="content project-content">
                  <h4 class="title"><a href="{% url 'portfolio:project' pk=item.id %}">{{ item.name }}</a></h4>
                  <span class="cat">{{ item.title }}</span>
                  <a href="{% url 'portfolio:project' pk=item.id %}" class="inline-btn">
                    <i class="far fa-arrow-right"></i>
                  </a>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Information Section -->
<div class="codeshift-card-section theme-light-bg pt-130">
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="codeshift-card-wrapper d-flex justify-content-between align-items-center">
          <div class="codeshift-card-box wow fadeInUp" data-wow-delay="00ms" data-wow-duration="800ms">
            <div class="icon">
              <img src="{% static 'assets/images/icons/card-icon-1.png' %}" alt="" />
            </div>
            <div class="content">
              <h4 class="title">{% trans 'Cross-Industry Expertise' %}</h4>
            </div>
            <div class="codeshift-dots">
              <span></span>
              <span></span>
              <span></span>
            </div>
          </div>
          <div class="codeshift-card-box codeshift-card-box__2 wow fadeInUp" data-wow-delay="200ms"
            data-wow-duration="800ms">
            <div class="icon">
              <img src="{% static 'assets/images/icons/card-icon-2.png' %}" alt="" />
            </div>
            <div class="content">
              <h4 class="title">{% trans 'Expertise & Leadership' %}</h4>
            </div>
            <div class="codeshift-dots">
              <span></span>
              <span></span>
              <span></span>
            </div>
          </div>
          <div class="codeshift-card-box codeshift-card-box__3 wow fadeInUp" data-wow-delay="500ms"
            data-wow-duration="800ms">
            <div class="icon">
              <img src="{% static 'assets/images/icons/card-icon-3.png' %}" alt="" />
            </div>
            <div class="content">
              <h4 class="title">{% trans 'Dedicate IT Solution' %}</h4>
            </div>
            <div class="codeshift-dots">
              <span></span>
              <span></span>
              <span></span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Brand Section -->
<div class="codeshift-brand-section pt-125 pb-130">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-xl-6">
        <div class="codeshift-section-heading text-center mb-60">
          <span class="sub-heading">{% trans 'we serve all industries' %}</span>
          <h2 class="heading">{% trans 'Top industries' %}</h2>
        </div>
      </div>
    </div>
    <div class="row justify-content-center mt-none-30">
      <div class="col-xl-3 col-lg-4 col-md-6 mt-30">
        <div class="codeshift-brand-box codeshift-brand-box__1 wow fadeInUp" data-wow-delay="0ms"
          data-wow-duration="800ms">
          <div class="icon">
            <img src="{% static 'assets/images/icons/brand-icon-1.png' %}" alt="" />
          </div>
          <div class="content">
            <h6 class="title">{% trans 'Travel & Tourism' %}</h6>
          </div>
        </div>
      </div>
      <div class="col-xl-3 col-lg-4 col-md-6 mt-30">
        <div class="codeshift-brand-box codeshift-brand-box__2 wow fadeInUp" data-wow-delay="200ms"
          data-wow-duration="800ms">
          <div class="icon">
            <img src="{% static 'assets/images/icons/brand-icon-2.png' %}" alt="" />
          </div>
          <div class="content">
            <h6 class="title">{% trans 'Industry & Finance' %}</h6>
          </div>
        </div>
      </div>
      <div class="col-xl-3 col-lg-4 col-md-6 mt-30">
        <div class="codeshift-brand-box codeshift-brand-box__3 wow fadeInUp" data-wow-delay="300ms"
          data-wow-duration="800ms">
          <div class="icon">
            <img src="{% static 'assets/images/icons/brand-icon-3.png' %}" alt="" />
          </div>
          <div class="content">
            <h6 class="title">{% trans 'Media & Entertainment' %}</h6>
          </div>
        </div>
      </div>
      <div class="col-xl-3 col-lg-4 col-md-6 mt-30">
        <div class="codeshift-brand-box codeshift-brand-box__4 wow fadeInUp" data-wow-delay="400ms"
          data-wow-duration="800ms">
          <div class="icon">
            <img src="{% static 'assets/images/icons/brand-icon-4.png' %}" alt="" />
          </div>
          <div class="content">
            <h6 class="title">{% trans 'Hotels & Restaurant' %}</h6>
          </div>
        </div>
      </div>
      <div class="col-xl-3 col-lg-4 col-md-6 mt-30">
        <div class="codeshift-brand-box codeshift-brand-box__5 wow fadeInUp" data-wow-delay="500ms"
          data-wow-duration="800ms">
          <div class="icon">
            <img src="{% static 'assets/images/icons/brand-icon-5.png' %}" alt="" />
          </div>
          <div class="content">
            <h6 class="title">{% trans 'Healthcare Solution' %}</h6>
          </div>
        </div>
      </div>
      <div class="col-xl-3 col-lg-4 col-md-6 mt-30">
        <div class="codeshift-brand-box codeshift-brand-box__6 wow fadeInUp" data-wow-delay="600ms"
          data-wow-duration="800ms">
          <div class="icon">
            <img src="{% static 'assets/images/icons/brand-icon-6.png' %}" alt="" />
          </div>
          <div class="content">
            <h6 class="title">{% trans 'E-learning & Education' %}</h6>
          </div>
        </div>
      </div>
      <div class="col-xl-3 col-lg-4 col-md-6 mt-30">
        <div class="codeshift-brand-box codeshift-brand-box__7 wow fadeInUp" data-wow-delay="700ms"
          data-wow-duration="800ms">
          <div class="icon">
            <img src="{% static 'assets/images/icons/brand-icon-7.png' %}" alt="" />
          </div>
          <div class="content">
            <h6 class="title">{% trans 'Web Development' %}</h6>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

server/apps/base/templates/base/layout.html
{% load static %}

{% load i18n %}

<!DOCTYPE html>
<html class="no-js" lang="en">

<head>
  <!-- Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="author" content="CodeShift" />
  <meta name="description" content="Technology & IT Solutions Service" />
  <meta name="keywords" content="CodeShift, Technology & IT Solutions Service, Web Development" />

  <!-- Title -->
  <title>CodeShift - Technology & IT Solutions Service </title>

  <!-- Favicon -->
  <link rel="shortcut icon" href="{% static 'assets/images/favicon/favicon.png' %}" type="images/x-icon" />
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/images/favicon/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/images/favicon/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/favicon/favicon-16x16.png' %}">

  <!-- Plugins -->
  <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/lightcase.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/meanmenu.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/jquery-ui.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/ukit.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/odometer.min.css' %}" />

  <!-- Stylesheets -->
  <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
</head>

<body>
  <!-- Loader -->
  <div id="codeshift-loading" class="codeshift-loader">
    <div class="codeshift-spinner">
      <div class="bounce1"></div>
      <div class="bounce2"></div>
      <div class="bounce3"></div>
    </div>
  </div>

  <!-- Header -->
  <header class="codeshift-header pt-50 pb-50" data-uk-sticky="top: 250; animation: uk-animation-slide-top;">
    <div class="container-fluid codeshift-container__fluid">
      <div class="row">
        <div class="col-xl-10 col-lg-4 col-sm-6 col-7 align-self-center">
          <div class="codeshift-logo-menu-wrapper">
            <a href="{% url 'base:home' %}" class="codeshift-logo">
              <img src="{% static 'assets/images/logo.png' %}" alt="LOGO" />
            </a>
            <div class="codeshift-menu-wrapper">
              <div class="codeshift-main-menu">
                <nav id="codeshift-navbar">
                  <ul>
                    <li class=""><a href="{% url 'base:home' %}">{% trans 'Home' %}</a></li>

                    <li class=""><a href="{% url 'portfolio:portfolio' %}">{% trans 'Our Projects' %}</a></li>

                    <li><a href="{% url 'base:about' %}">{% trans 'About' %}</a></li>

                    <li class="menu-item-has-children">
                      <a href="#">{% trans 'Language' %}</a>
                      <ul class="sub-menu">
                        {% get_available_languages as languages %}
                        {% get_current_language as current_lang %}
                        {% with "/"|add:current_lang as redundant %}
                        {% for lan in languages %}
                        <li><a href="/{{ lan.0 }}{{ request.get_full_path|cut:redundant }}">{{ lan.1 }}</a></li>
                        {% endfor %}
                        {% endwith %}
                      </ul>
                    </li>
                  </ul>
                </nav>
              </div>
              <a href="{% url 'base:contact' %}" class="codeshift-btn">{% trans 'Contact' %}<span></span></a>
            </div>
          </div>
        </div>
        <div class="col-xl-2 col-lg-8 col-sm-6 col-5 align-self-center">
          <div class="right-element">
            <ul class="list-unstyled d-flex align-items-center">
              <li class="sideinfo-trigger" data-sideinfo-trigger>
                <span></span>
                <span></span>
                <span></span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Overlay -->
  <div class="codeshift-overlay"></div>

  <!-- Mobile Sidebar -->
  <aside class="side-info-wrapper mm-only">
    <nav>
      <div class="nav" id="nav-tab" role="tablist">
        <a class="nav-link active" id="menu-tab-1-tab" data-bs-toggle="tab" href="#menu-tab-1" role="tab"
          aria-controls="menu-tab-1" aria-selected="true">Menu</a>
        <a class="nav-link" id="menu-tab-2-tab" data-bs-toggle="tab" href="#menu-tab-2" role="tab"
          aria-controls="menu-tab-2" aria-selected="false">Info</a>
      </div>
    </nav>
    <div class="side-info__wrapper d-flex align-items-center justify-content-between">
      <div class="side-info__logo">
        <a href="{% url 'base:home' %}">
          <img src="{% static 'assets/images/logo.png' %}" alt="logo" />
        </a>
      </div>
      <div class="side-info__close">
        <a href="javascript:void(0);"><i class="far fa-times"></i></a>
      </div>
    </div>
    <div class="tab-content" id="nav-tabContent">
      <div class="tab-pane fade show active" id="menu-tab-1" role="tabpanel" aria-labelledby="menu-tab-1-tab">
        <div class="codeshift-mobile-menu"></div>
      </div>
      <div class="tab-pane fade" id="menu-tab-2" role="tabpanel" aria-labelledby="menu-tab-2-tab">
        <div class="side-info">
          <div class="side-info__content mb-35">
            <h4 class="title mb-10">{% trans 'About us' %}</h4>
            <p>
              {% blocktrans trimmed %}
              CodeShift: Your Trusted Digital Solutions Partner. With over 6 years of experience in
              website and mobile app development, we deliver innovative and high-quality digital products
              that help businesses connect with their target audience. Our team of experienced professionals
              is passionate about digital solutions and committed to delivering outstanding results and exceptional
              customer service. Let us help you bring your vision to life. Choose CodeShift for your digital needs.
              {% endblocktrans %}
            </p>
            <a class="codeshift-btn codeshift-btn__small mt-20" href="{% url 'base:contact' %}">
              {% trans 'Contact us' %}
              <span></span>
            </a>
          </div>
          <div class="contact__info--wrapper mt-15">
            <h4 class="title mb-15">{% trans 'Contact us' %}</h4>
            <ul class="contact__info list-unstyled">
              <li>
                <span><i class="fas fa-map-marker-alt"></i></span>
                <p>{{ address }}</p>
              </li>
              <li>
                <span><i class="fas fa-phone"></i></span>
                <p>{{ phone }}</p>
              </li>
              <li>
                <span><i class="fas fa-envelope-open-text"></i></span>
                <p>{{ email }}</p>
              </li>
            </ul>
          </div>
          <div class="codeshift-social-links mt-30">
            <a href="{{ facebook }}"><i class="fab fa-facebook-f"></i></a>
            <a href="{{ instagram }}"><i class="fab fa-instagram"></i></a>
          </div>
        </div>
      </div>
    </div>
  </aside>

  <!-- Desktop Sidebar -->
  <aside class="side-info-wrapper show-all">
    <div class="side-info__wrapper d-flex align-items-center justify-content-between">
      <div class="side-info__logo">
        <a href="{% url 'base:home' %}">
          <img src="{% static 'assets/images/logo.png' %}" alt="logo" />
        </a>
      </div>
      <div class="side-info__close">
        <a href="javascript:void(0);"><i class="far fa-times"></i></a>
      </div>
    </div>
    <div class="side-info">
      <div class="side-info__content mb-35">
        <h4 class="title mb-10">{% trans 'About us' %}</h4>
        <p>
          {% blocktrans trimmed %}
          CodeShift: Your Trusted Digital Solutions Partner. With over 6 years of experience in
          website and mobile app development, we deliver innovative and high-quality digital products
          that help businesses connect with their target audience. Our team of experienced professionals
          is passionate about digital solutions and committed to delivering outstanding results and exceptional
          customer service. Let us help you bring your vision to life. Choose CodeShift for your digital needs.
          {% endblocktrans %}
        </p>
        <a class="codeshift-btn codeshift-btn__small mt-20" href="{% url 'base:contact' %}">{% trans 'Contact us'
          %}<span></span></a>
      </div>
      <div class="contact__info--wrapper mt-15">
        <h4 class="title mb-15">{% trans 'Contacts' %}</h4>
        <ul class="contact__info list-unstyled">
          <li>
            <span><i class="fas fa-map-marker-alt"></i></span>
            <p>{{ address }}</p>
          </li>
          <li>
            <span><i class="fas fa-phone"></i></span>
            <p>{{ phone }}</p>
          </li>
          <li>
            <span><i class="fas fa-envelope-open-text"></i></span>
            <p>{{ email }}</p>
          </li>
        </ul>
      </div>
      <div class="codeshift-social-links mt-30">
        <a href="{{ facebook }}"><i class="fab fa-facebook-f"></i></a>
        <a href="{{ instagram }}"><i class="fab fa-instagram"></i></a>
      </div>
    </div>
  </aside>

  {% block content %}{% endblock content %}

  <!-- Footer -->
  <footer class="codeshift-footer theme-light-bg pt-95">
    <div class="codeshift-footer-widgets">
      <div class="container">
        <div class="row mt-none-30">
          <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 codeshift-custom-col mt-30">
            <div class="widget">
              <div class="about-widget">
                <a href="{% url 'base:home' %}" class="codeshift-footer-logo mb-35">
                  <img src="{% static 'assets/images/logo.png' %}" alt="CodeShift" />
                </a>
                <p><i class="far fa-map-marker-alt"></i> {{ address }}</p>
                <p><i class="far fa-envelope"></i> {{ email }}</p>
                <div class="codeshift-social-links mt-40">
                  <a href="{{ facebook }}"><i class="fab fa-facebook-f"></i></a>
                  <a href="{{ instagram }}"><i class="fab fa-instagram"></i></a>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 codeshift-custom-col mt-30">
            <div class="widget">
              <h3 class="widget-title">{% trans 'Services' %}</h3>
              <ul>
                {% for category in categories %}
                <li>
                  <a href="{% url 'portfolio:category' pk=category.id %}">{{ category.name }}</a>
                </li>
                {% endfor %}
              </ul>
            </div>
          </div>
          <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 codeshift-custom-col mt-30">
            <div class="widget">
              <h3 class="widget-title">{% trans 'Information' %}</h3>
              <ul>
                <li><a href="{% url 'base:about' %}">{% trans 'About' %}</a></li>
                <li><a href="{% url 'base:contact' %}">{% trans 'Contact' %}</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="codeshift-copyright">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <p>Copyright &copy; <span id="copyright-date"></span> CodeShift, {% trans "All Rights Reserved" %}.</p>
          </div>
          <div class="col-md-4">
            <div class="codeshift-backtotop">
              <button data-codeshift-backtotop><i class="far fa-angle-up"></i> {% trans "Go On Top" %}</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>

  <!-- Plugins -->
  <script src="{% static 'assets/js/jquery-2.2.4.min.js' %}"></script>
  <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/js/jquery.meanmenu.min.js' %}"></script>
  <script src="{% static 'assets/js/uikit.js' %}"></script>
  <script src="{% static 'assets/js/jquery.nice-select.min.js' %}"></script>
  <script src="{% static 'assets/js/lightcase.js' %}"></script>
  <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'assets/js/jquery.easing.min.js' %}"></script>
  <script src="{% static 'assets/js/waypoint.js' %}"></script>
  <script src="{% static 'assets/js/imagesloaded.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/js/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/js/js-jquery.knob.js' %}"></script>
  <script src="{% static 'assets/js/js-jquery.appear.js' %}"></script>
  <script src="{% static 'assets/js/odometer.min.js' %}"></script>
  <script src="{% static 'assets/js/wow.min.js' %}"></script>

  <!-- Main JS -->
  <script src="{% static 'assets/js/main.js' %}"></script>

  {% block scripts %}{% endblock scripts %}
</body>

</html>