server/apps/base/urls.py
from django.urls import path

from server.apps.base.views import AboutView, ContactView, HomeView

app_name = "base"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact/", ContactView.as_view(), name="contact"),
]

server/apps/portfolio/urls.py
from django.urls import path

from server.apps.portfolio.views import CategoryView, PortfolioView, ProjectView

app_name = "portfolio"

urlpatterns = [
    path("", PortfolioView.as_view(), name="portfolio"),
    path("<int:pk>/", ProjectView.as_view(), name="project"),
    path("category/<int:pk>/", CategoryView.as_view(), name="category"),
]

server/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path

from server.apps.base.views import IndexView

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path("", include("server.apps.base.urls", namespace="base")),
    path("portfolio/", include("server.apps.portfolio.urls", namespace="portfolio")),
)

urlpatterns += [
    path("i18n/", include("django.conf.urls.i18n")),
]

urlpatterns += [path("", IndexView.as_view(), name="index")]

if "rosetta" in settings.INSTALLED_APPS:
    urlpatterns += [path("translations/", include("rosetta.urls"))]

# Django Health Check
urlpatterns += [
    path("health/", include("health_check.urls")),
]

if settings.DEBUG:
    from django.conf.urls.static import static  # noqa: WPS433

    # Django Debug Toolbar
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

    # Serving media files in development only:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

server/apps/portfolio/models.py
from django.db import models


class Project(models.Model):
    """Model definition for Project."""

    name = models.CharField(max_length=50)
    title = models.CharField(max_length=250)

    category = models.ForeignKey("Category", on_delete=models.CASCADE, related_name="projects")

    client = models.CharField(max_length=50)
    website = models.CharField(max_length=250, blank=True, null=True)
    banner = models.ImageField(upload_to="portfolio/banners")
    cover = models.ImageField(upload_to="portfolio/covers")

    description = models.TextField()

    modified_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        """Meta definition for Project."""

        verbose_name = "Project"
        verbose_name_plural = "Projects"

    def __str__(self):
        """Unicode representation of Project."""
        return f"{self.name}"

    def image(self):
        return self.images.first().image

    def previous(self):
        if self.pk == Project.objects.first().pk:
            return None

        return Project.objects.filter(pk__lt=self.pk).last()

    def next(self):
        if self.pk == Project.objects.last().pk:
            return None

        return Project.objects.filter(pk__gt=self.pk).first()


class ProjectPoint(models.Model):
    """Model definition for ProjectPoint."""

    project = models.ForeignKey("Project", on_delete=models.CASCADE, related_name="points")
    point = models.CharField(max_length=250)

    class Meta:
        """Meta definition for ProjectPoint."""

        verbose_name = "ProjectPoint"
        verbose_name_plural = "ProjectPoints"

    def __str__(self):
        """Unicode representation of ProjectPoint."""
        return f"{self.point}"


class ProjectImage(models.Model):
    """Model definition for ProjectImage."""

    image = models.ImageField(upload_to="portfolio/images")
    project = models.ForeignKey("Project", on_delete=models.CASCADE, related_name="images")

    class Meta:
        """Meta definition for ProjectImage."""

        verbose_name = "ProjectImage"
        verbose_name_plural = "ProjectImages"

    def __str__(self):
        """Unicode representation of ProjectImage."""
        return f"{self.project.name}"


class Category(models.Model):
    """Model definition for Category."""

    name = models.CharField(max_length=50)

    class Meta:
        """Meta definition for Category."""

        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        """Unicode representation of Category."""
        return f"{self.name}"

server/apps/portfolio/views.py
from django.views.generic import TemplateView

from server.apps.portfolio.models import Category, Project


class PortfolioView(TemplateView):
    """Portfolio view."""

    template_name = "portfolio/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["title"] = "Portfolio"

        context["projects"] = Project.objects.all().order_by("-modified_at")

        return context


class ProjectView(TemplateView):
    """Project view."""

    template_name = "portfolio/project.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["title"] = "Project Details"

        context["project"] = Project.objects.get(pk=kwargs["pk"])

        return context


class CategoryView(TemplateView):
    """Category view."""

    template_name = "portfolio/category.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["category"] = Category.objects.get(pk=kwargs["pk"])

        context["title"] = context["category"].name

        return context

server/apps/portfolio/templates/portfolio/category.html
{% extends 'base/layout.html' %}

{% load static %}

{% load i18n %}

{% block content %}
<!-- Breadcrumb -->
<section class="breadcrumb-area fix theme-dark-bg bg_img">
  <div class="small-shape small-shape__1">
    <img src="{% static 'assets/images/shapes/small-shape-1.png' %}" alt="" />
  </div>
  <div class="small-shape small-shape__2">
    <img src="{% static 'assets/images/shapes/small-shape-2.png' %}" alt="" />
  </div>
  <div class="small-shape small-shape__3">
    <img src="{% static 'assets/images/shapes/small-shape-3.png' %}" alt="" />
  </div>
  <div class="small-shape small-shape__4">
    <img src="{% static 'assets/images/shapes/small-shape-4.png' %}" alt="" />
  </div>
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="codeshift-breadcrumb-wrapper position-relative pt-190 pb-190">
          <h2 class="page-title">{{ category.name }}</h2>
          <div class="codeshift-breadcrumb breadcrumbs">
            <ul class="list-unstyled d-flex align-items-center">
              <li class="codeshift-item duxinbcrumb-begin">
                <a href="{% url 'base:home' %}"><span>{% trans 'Home Page' %}</span></a>
              </li>
              <li class="codeshift-item duxinbcrumb-begin">
                <a href="{% url 'portfolio:portfolio' %}"><span>{% trans 'Portfolio' %}</span></a>
              </li>
              <li class="codeshift-item duxinbcrumb-end">
                <span>{{category.name}} </span>
              </li>
            </ul>
          </div>
          <div class="right-img">
            <img src="{% static 'assets/images/bg/breadcrumb-bg.png' %}" alt="" />
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Projects Section -->
<div class="codeshift-project-section codeshift-project-section__style-2 pt-130 pb-120">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-xl-6">
        <div class="codeshift-section-heading codeshift-section-heading__style-2 text-center mb-50">
          <span class="sub-heading">{{category.name}}</span>
          <h2 class="heading">{% trans 'Our recent projects' %}</h2>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xl-12">
        <div class="codeshift-project-wrapper mt-50">
          <div class="row codeshift-project-grid mt-none-30">
            {% for project in category.projects.all %}
            <div class="col-xl-6 col-lg-6 mt-30 grid">
              <div class="codeshift-project-item codeshift-project-item__style-2">
                <div class="content">
                  <h4 class="title"><a href="{% url 'portfolio:project' pk=project.id %}">{{ project.name }}</a></h4>
                  <a href="{% url 'portfolio:project' pk=project.id %}" class="inline-btn">
                    <i class="far fa-arrow-right"></i>
                  </a>
                </div>
                <div class="thumb">
                  <img class="portfolio-img" src="{{ project.cover.url }}" alt="" />
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

server/apps/portfolio/templates/portfolio/index.html
{% extends 'base/layout.html' %}

{% load static %}

{% load i18n %}

{% block content %}
<!-- Breadcrumb -->
<section class="breadcrumb-area fix theme-dark-bg bg_img">
  <div class="small-shape small-shape__1">
    <img src="{% static 'assets/images/shapes/small-shape-1.png' %}" alt="" />
  </div>
  <div class="small-shape small-shape__2">
    <img src="{% static 'assets/images/shapes/small-shape-2.png' %}" alt="" />
  </div>
  <div class="small-shape small-shape__3">
    <img src="{% static 'assets/images/shapes/small-shape-3.png' %}" alt="" />
  </div>
  <div class="small-shape small-shape__4">
    <img src="{% static 'assets/images/shapes/small-shape-4.png' %}" alt="" />
  </div>
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="codeshift-breadcrumb-wrapper position-relative pt-190 pb-190">
          <h2 class="page-title">{% trans 'Portfolio' %}</h2>
          <div class="codeshift-breadcrumb breadcrumbs">
            <ul class="list-unstyled d-flex align-items-center">
              <li class="codeshift-item duxinbcrumb-begin">
                <a href="{% url 'base:home' %}"><span>{% trans 'Home Page' %}</span></a>
              </li>
              <li class="codeshift-item duxinbcrumb-end">
                <span>{% trans 'Portfolio' %} </span>
              </li>
            </ul>
          </div>
          <div class="right-img">
            <img src="{% static 'assets/images/bg/breadcrumb-bg.png' %}" alt="" />
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Projects Section -->
<div class="codeshift-project-section codeshift-project-section__style-2 pt-130 pb-120">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-xl-6">
        <div class="codeshift-section-heading codeshift-section-heading__style-2 text-center mb-50">
          <span class="sub-heading">{% trans 'Portfolio' %}</span>
          <h2 class="heading">{% trans 'Our recent projects' %}</h2>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xl-12">
        <div class="codeshift-project-wrapper mt-50">
          <div class="row codeshift-project-grid mt-none-30">
            {% for project in projects %}
            <div class="col-xl-6 col-lg-6 cat-{{ project.category.id }} mt-30 grid">
              <div class="codeshift-project-item codeshift-project-item__style-2">
                <div class="content">
                  <h4 class="title"><a href="{% url 'portfolio:project' pk=project.id %}">{{ project.name }}</a></h4>
                  <a href="{% url 'portfolio:project' pk=project.id %}" class="inline-btn">
                    <i class="far fa-arrow-right"></i>
                  </a>
                </div>
                <div class="thumb">
                  <img class="portfolio-img" src="{{ project.cover.url }}" alt="" />
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
      {% comment %} <div class="col-xl-12 text-center mt-60">
        <a href="#" class="codeshift-btn">Discover More Projects</a>
      </div> {% endcomment %}
    </div>
  </div>
</div>
{% endblock content %}


{% block scripts %}
<script>
  if (window.location.href.includes("category")) {
    let category_id = window.location.href.split("/").pop().slice(10);
    document.querySelector(`#cat-${category_id}`).click();
  }
</script>
{% endblock scripts %}

server/apps/portfolio/templates/portfolio/project.html
{% extends 'base/layout.html' %}

{% load static %}

{% load i18n %}

{% block content %}
<!-- Breadcrumb -->
<section class="breadcrumb-area fix theme-dark-bg bg_img">
  <div class="small-shape small-shape__1">
    <img src="{% static 'assets/images/shapes/small-shape-1.png' %}" alt="" />
  </div>
  <div class="small-shape small-shape__2">
    <img src="{% static 'assets/images/shapes/small-shape-2.png' %}" alt="" />
  </div>
  <div class="small-shape small-shape__3">
    <img src="{% static 'assets/images/shapes/small-shape-3.png' %}" alt="" />
  </div>
  <div class="small-shape small-shape__4">
    <img src="{% static 'assets/images/shapes/small-shape-4.png' %}" alt="" />
  </div>
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="codeshift-breadcrumb-wrapper position-relative pt-190 pb-190">
          <h2 class="page-title">{{ project.name }}</h2>
          <div class="codeshift-breadcrumb breadcrumbs">
            <ul class="list-unstyled d-flex align-items-center">
              <li class="codeshift-item duxinbcrumb-begin">
                <a href="{% url 'base:home' %}"><span>{% trans 'Home Page' %}</span></a>
              </li>
              <li class="codeshift-item duxinbcrumb-begin">
                <a href="{% url 'portfolio:portfolio' %}"><span>{% trans 'Portfolio' %}</span></a>
              </li>
              <li class="codeshift-item duxinbcrumb-end">
                <span>{{ project.name }} </span>
              </li>
            </ul>
          </div>
          <div class="right-img">
            <img src="{% static 'assets/images/bg/breadcrumb-bg.png' %}" alt="" />
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Project Details Section -->
<div class="codeshift-details-page pt-130 pb-130">
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="details-thumb mb-50">
          <img class="portfolio-details-banner-img" src="{{ project.banner.url }}" alt="" />
        </div>
        <div class="details-content">
          <h2 class="codeshift-title mb-25">{{ project.title }}</h2>
          <p>{{ project.description|linebreaks }}</p>
          <div class="navigation-border pb-25"></div>
          <ul class="list-unstyled portfolio-meta">
            <li><span class="label">{% trans 'Client' %} :</span> <span class="text">{{ project.client }}</span></li>
            <li><span class="label">{% trans 'Website' %} :</span> <span class="text">{{ project.website }}</span></li>
            <li><span class="label">{% trans 'Category' %} :</span> <span class="text">{{ project.category.name}}</span></li>
          </ul>
        </div>
      </div>
      <div class="col-xl-12">
        <div class="portfolio-details-carousel mt-45 owl-carousel" data-portfolio-details-carousel>
          {% for item in project.images.all %}
          <!-- Item -->
          <div class="portfolio-details-carousel__item">
            <img class="portfolio-details-img" src="{{ item.image.url }}" alt="" />
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="col-xl-12 mt-90">
        <h2 class="codeshift-title mb-25">{% trans 'Project requirement' %}</h2>
        <div class="row mt-none-15">
          <div class="col-12 mt-15">
            <ul class="list-unstyled Language-list-item d-flex row">
              {% for item in project.points.all %}
              <li class="col-6">
                <img src="{% static 'assets/images/icons/double-arrow.png' %}" alt="" />
                {{ item.point }}
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>

        <div class="navigation-border mt-50"></div>
        <div class="codeshift-next-prev-wrapper mt-50">
          {% if project.previous %}
          <a href="{% url 'portfolio:project' pk=project.previous.id %}"
            class="codeshift-next-prev codeshift-next-prev__prev">
            <span class="icon"><i class="far fa-arrow-left"></i></span><span class="text">{% trans 'Previous' %}</span>
          </a>
          {% endif %}
          {% if project.next %}
          <a href="{% url 'portfolio:project' pk=project.next.id %}"
            class="codeshift-next-prev codeshift-next-prev__next">
            <span class="text">{% trans 'Next' %}</span><span class="icon"><i class="far fa-arrow-right"></i></span>
          </a>
          {% endif %}
        </div>
      </div>
      <div class="col-xl-12 mt-90">
        <h2 class="codeshift-title mb-40">{% trans 'Our similar projects' %}</h2>
        <div class="codeshift-project-carousel owl-carousel codeshift-slide-nav codeshift-slide-nav__style-3"
          data-project-carousel>
          {% for item in project.category.projects.all %}
          {% if item.id != project.id %}
          <!-- Item -->
          <div class="codeshift-project-item codeshift-project-item__style-2">
            <div class="content">
              <h4 class="title">
                <a href="{% url 'portfolio:project' pk=item.id %}">{{ item.name }}</a>
              </h4>
              <a href="{% url 'portfolio:project' pk=item.id %}" class="inline-btn">
                <i class="far fa-arrow-right"></i>
              </a>
            </div>
            <div class="thumb">
              <img src="{{ item.cover.url }}" alt="" />
            </div>
          </div>
          {% endif %}
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}